const nameList = [
  'Acorn Hall',
  'House of the Undying',
  'Andalos',
  'Dorne',
  'Ib',
  'Antler River',
  'Dornish Marches',
  'Inn at the Crossroads',
  'Antlers',
  'Dothraki Sea',
  'Iron Islands',
  'The Arbor',
  'Dragonpit',
  'Ironmans Bay',
  'Arsenal of Braavos',
  'Dragonstone(island)',
  'Isle of Faces',
  'Ashemark',
  'Driftmark',
  'Isle of Tears',
  'Ashford',
  'Duskendale',
  'Isle of the Gods',
  'Asshai',
  'Karhold',
  'The Axe',
  'Evenfall Hall',
  'Kings Gate',
  'Bandallon',
  'The Eyrie',
  'Kings Landing',
  'The Banefort',
  'Fair Isle',
  'Kingsgrave',
  'Barrowlands',
  'Faircastle',
  'Kingsroad',
  'Barrowton',
  'Fairmarket',
  'Kingswood',
  'Barter Beach',
  'Feastfires',
  'Land of Always Winter',
  'Basilisk Isles',
  'Felwood',
  'Lannisport',
  'Bay of Ice',
  'The Fingers',
  'Last Hearth',
  'Bay of Seals',
  'Fist of the First Men',
  'Last River',
  'Bayasabhad',
  'Flatlands',
  'Lemonwood',
  'Bear Island',
  'Flea Bottom',
  'Lhazar',
  'Beyond the Wall',
  'Flints Finger',
  'Lonely Hills',
  'Bhorash',
  'Forest of Qohor',
  'Long Barrow',
  'The Bite',
  'Free Cities',
  'Long Bridge',
  'Bitterbridge',
  'Frostfangs',
  'Long Lake',
  'Black Cells',
  'Frozen Shore',
  'Long Table',
  'Black Cliffs',
  'Garden of Bones',
  'Lorath',
  'Black Wall',
  'Ghiscari Strait',
  'Lord Harroways Town',
  'Blackcrown',
  'Ghost Hill',
  'Lordsport',
  'Blackhaven',
  'The Gift',
  'Lys',
  'Blackmont',
  'Gods Eye',
  'Maegors Holdfast',
  'Blacktyde',
  'Godsgrace',
  'Maidenpool',
  'Blackwater Bay',
  'Godsway',
  'Maidenvault',
  'Blackwater Rush',
  'Golden Fields',
  'Milkwater',
  'Blazewater Bay',
  'Golden Tooth',
  'Mistwood',
  'Bloody Gate',
  'Goldengrove',
  'Moat Cailin',
  'Bone Mountains',
  'Grassy Vale'
];
const totalName = nameList.length;

module.exports.generateListingName = () => {
  return nameList[Math.floor(Math.random()*totalName)];
}